// SPORTSBOOK PARSERS
// To add a new sportsbook: add a new case in the switch statement inside buildParsingPrompt()
// with specific instructions for how that sportsbook displays odds, descriptions, and bet layout

/**
 * Builds a Claude prompt for parsing a betslip screenshot.
 * @param {string|null} hint - Optional detected sportsbook name (e.g. 'fanduel', 'draftkings')
 * @returns {string} - The full prompt to send to Claude
 */
function buildParsingPrompt(hint) {
    const normalizedHint = hint ? hint.toLowerCase().replace(/\s/g, '') : null;

    let sbInstructions = '';

    switch (normalizedHint) {
        case 'fanduel':
            sbInstructions = `
SPORTSBOOK: FanDuel — two possible screenshot styles, both are FanDuel:

Style 1 - Manual screenshot of FanDuel app (dark background):
- A "X leg parlay" or "Same Game Parlay" header with combined odds shown top right = this is ONE single bet
- Individual legs are expanded below the header showing their own individual odds and matchup info — these are leg odds only, IGNORE them entirely
- Use ONLY the header combined odds as the bet odds
- Description = the combined leg summary text shown just below the header
- A vertical dot or line connector between legs confirms they are all part of the same single bet — do not split them into separate bets

Style 2 - FanDuel native share card (blue gradient header):
- Generated by FanDuel's built-in share feature
- A blue gradient header card showing the bet type and combined odds in the top right = this is ONE single bet
- Legs are displayed inside a dark card beneath the blue header
- Use the header combined odds as the bet odds
- Description = all legs combined into one string
- This is still FanDuel, not a third-party app — treat it the same way

For both styles: return exactly ONE bet object for the entire slip, not one per leg.`;
            break;

        case 'draftkings':
            sbInstructions = `
SPORTSBOOK: DraftKings
- Clean dark UI with no SGP badge
- Each bet block shows player name bold at the top, prop description below it
- Matchup and game time appear at the bottom of each block
- Odds appear in the top right of each block
- Ladder-style bets show the same player with escalating thresholds as separate individual blocks — treat each as its own separate bet`;
            break;

        case 'fanatics':
            sbInstructions = `
SPORTSBOOK: Fanatics
- Similar layout to DraftKings
- Odds are displayed in the top right of each bet block
- Player name and prop description are shown clearly in each block
- Treat each visible bet block as a separate individual bet`;
            break;

        default:
            sbInstructions = `
SPORTSBOOK: Unknown — apply general rules:
- Look for odds values in American format (e.g. -110, +150) typically positioned near the top right of each bet block
- Each visually distinct bet block should be treated as a separate bet
- Extract the most descriptive text in the block as the description`;
            break;
    }

    return `You are a sports betting assistant. Analyze this betslip screenshot and extract all the individual bets shown.
${sbInstructions}

Return a JSON array of bet objects. Each object must have exactly these fields:
- "description": string — short concise bet description following the formatting rules below
- "odds": number — American format odds as an integer (e.g. -110, 150, -350)
- "sport": string — the sport (e.g. "NBA", "NFL", "MLB", "NHL", "CBB", "CFB", "Soccer") — infer from context if not explicitly shown; if a single bet or parlay spans multiple different sports, use "Multisport"
- "betType": string — one of: "SGP", "prop", "spread", "moneyline", "total", "parlay", "teaser", "future"

Description formatting rules:
- Players: last name only (e.g. "Johnson" not "Cam Johnson", "Dort" not "Luguentz Dort")
- Teams: last word of team name only (e.g. "Panthers" not "Florida Panthers", "Knights" not "Vegas Golden Knights")
- Shorten stat descriptions naturally (e.g. "4+ Threes", "10+ Pts", "1+ TD", "Over 224.5")
- Remove all matchup context, game location, and game time
- For parlays and SGPs: combine all legs on one line separated by " + " (e.g. "Johnson 25+ Pts + Dort 1+ Threes")
- One clean concise line per bet

General rules:
- Return bets in visual order top to bottom as they appear in the screenshot
- If a bet has no readable odds, skip it
- Do NOT include the overall parlay odds — only extract individual bet legs or standalone bets
- Return ONLY valid JSON — no markdown, no explanation, no backticks, no code fences
- The response must start with [ and end with ]`;
}

module.exports = { buildParsingPrompt };
